version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/" # Location of your Terraform configuration
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "terraform"
      - "dependencies"
